Repository 2025TUKCOMCD/HalfFifty, pull requests merged in 2025-04, with the labels that each got.

#194 Fix : 수어인식 List 형태 변경
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/domain/DTO/RequestSignLanguageDTO.java
Labels: 🐈‍⬛ BackEnd

#196 feat: 지문자에 맞춘 손 랜드마크 형식(한 손 인식)을 단어 인식 형식으로 변경(두 손 인식)
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-2.imageset/tutorial-2.png
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-2.imageset/tutorial-3.png
  HalfFifty_FE/HalfFifty_FE/View/ChipsTranslationResultView.swift
  HalfFifty_FE/HalfFifty_FE/View/ChipsView.swift
  HalfFifty_FE/HalfFifty_FE/View/ContentView.swift
  HalfFifty_FE/HalfFifty_FE/View/FlexibleView.swift
  HalfFifty_FE/HalfFifty_FE/View/MainView.swift
  HalfFifty_FE/HalfFifty_FE/View/MenuView.swift
  HalfFifty_FE/HalfFifty_FE/View/TutorialView.swift
  HalfFifty_FE/HalfFifty_FE/ViewController/CameraViewController.swift
  HalfFifty_FE/HalfFifty_FE/ViewModel/UserViewModel.swift
  HalfFifty_FE/HalfFifty_Watch Watch AppTests/HalfFifty_Watch_Watch_AppTests.swift
  HalfFifty_FE/HalfFifty_Watch Watch AppUITests/HalfFifty_Watch_Watch_AppUITests.swift
  HalfFifty_FE/HalfFifty_Watch Watch AppUITests/HalfFifty_Watch_Watch_AppUITestsLaunchTests.swift
Labels: 🥰 FrontEnd, 🔨 Refactor

#198 [Test] 애플워치 연동 테스트
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcshareddata/xcschemes/HalfFifty_FE.xcscheme
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcshareddata/xcschemes/HalfFifty_Watch Watch AppTests.xcscheme
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcuserdata/minmin.xcuserdatad/xcschemes/xcschememanagement.plist
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-2.imageset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-3.imageset/Contents.json
  HalfFifty_FE/HalfFifty_Watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  HalfFifty_FE/Podfile
  HalfFifty_FE/Podfile.lock
  documents/S3-7 김민지, 문창현, 유수현, 임정윤 2차 설계서.pptx
Labels: ✅ Test

#180 Feat: 고객센터 페이지 API 연동
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcshareddata/xcschemes/HalfFifty_FE.xcscheme
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcshareddata/xcschemes/HalfFifty_Watch Watch AppTests.xcscheme
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcuserdata/minmin.xcuserdatad/xcschemes/xcschememanagement.plist
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-2.imageset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-3.imageset/Contents.json
  HalfFifty_FE/HalfFifty_FE/View/Setting/CustomerCenterView.swift
  HalfFifty_FE/HalfFifty_FE/View/Setting/InquiryView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  HalfFifty_FE/Podfile
  HalfFifty_FE/Podfile.lock
  documents/S3-7 김민지, 문창현, 유수현, 임정윤 2차 설계서.pptx
Labels: ✨ Feature, 🥰 FrontEnd
