Repository 2025TUKCOMCD/HalfFifty, pull requests merged in 2025-01, with the labels that each got.

#15 Chore: FE 개발환경 초기설정
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.xcworkspace/xcuserdata/minmin.xcuserdatad/UserInterfaceState.xcuserstate
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcuserdata/minmin.xcuserdatad/xcschemes/xcschememanagement.plist
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/AccentColor.colorset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/AppIcon.appiconset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/Contents.json
  HalfFifty_FE/HalfFifty_FE/ContentView.swift
  HalfFifty_FE/HalfFifty_FE/HalfFifty_FEApp.swift
  HalfFifty_FE/HalfFifty_FE/Preview Content/Preview Assets.xcassets/Contents.json
Labels: ⚙️ Setting

#22 Feat : BE 개발환경 프로젝트 생성
  .idea/.gitignore
  .idea/HalfFifty.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  HalfFifty_BE/.gitattributes
  HalfFifty_BE/.gitignore
  HalfFifty_BE/build.gradle
  HalfFifty_BE/gradle/wrapper/gradle-wrapper.jar
  HalfFifty_BE/gradle/wrapper/gradle-wrapper.properties
  HalfFifty_BE/gradlew
  HalfFifty_BE/gradlew.bat
  HalfFifty_BE/settings.gradle
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HalfFiftyBeApplication.java
  HalfFifty_BE/src/main/resources/application.properties
  HalfFifty_BE/src/test/java/HalfFifty/HalfFifty_BE/HalfFiftyBeApplicationTests.java
Labels: ⚙️ Setting

#25 Fix : Github 불필요한 파일 삭제
  .idea/.gitignore
  .idea/HalfFifty.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  HalfFifty_BE/.gitignore
Labels: ⚙️ Setting

#29 Chore : BE 프로젝트 세팅
  HalfFifty_BE/.gitignore
  HalfFifty_BE/src/main/resources/application.properties
Labels: ⚙️ Setting

#33 Chore : Github 연동
  HalfFifty_AI/test.py
Labels: ⚙️ Setting

#35 Design: Splash 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.xcworkspace/xcuserdata/minmin.xcuserdatad/UserInterfaceState.xcuserstate
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/logo.imageset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/logo.imageset/logo.svg
  HalfFifty_FE/HalfFifty_FE/ContentView.swift
  HalfFifty_FE/HalfFifty_FE/SplashView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#94 Design: 메인 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.xcworkspace/xcuserdata/minmin.xcuserdatad/UserInterfaceState.xcuserstate
  HalfFifty_FE/HalfFifty_FE/MainView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#95 Feat: 메인 페이지 카메라 기능 구현
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.xcworkspace/xcuserdata/minmin.xcuserdatad/UserInterfaceState.xcuserstate
  HalfFifty_FE/HalfFifty_FE/CameraView.swift
  HalfFifty_FE/HalfFifty_FE/MainView.swift
Labels: ✨ Feature, 🥰 FrontEnd, 🎨 Html&css

#96 Test: 수어 모델링 코드 업로드
  HalfFifty_AI/config.py
  HalfFifty_AI/data_processing.py
  HalfFifty_AI/data_split.py
  HalfFifty_AI/evaluate_model.py
  HalfFifty_AI/googlemount.py
  HalfFifty_AI/label_index.py
  HalfFifty_AI/lstm_model.py
  HalfFifty_AI/model_saving.py
  HalfFifty_AI/model_training.py
  HalfFifty_AI/one_hot_encoding.py
  HalfFifty_AI/reshape.py
  HalfFifty_AI/shape_checker.py
  HalfFifty_AI/training_visualization.py
  HalfFifty_AI/unique_labels.py
Labels: ✅ Test

#97 Feat : Docker를 이용한 AWS EC2 배포
  HalfFifty_BE/Dockerfile
  HalfFifty_BE/build.gradle
  HalfFifty_BE/docker-compose.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🌏 Deploy

#103 Feat : CI/CD
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/Dockerfile
  HalfFifty_BE/docker-compose.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🌏 Deploy, 🐈‍⬛ BackEnd

#104 Test : CI/CD
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, 🌏 Deploy, ✅ Test, 🐈‍⬛ BackEnd

#105 Design: 스마트워치 메인 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.xcworkspace/xcuserdata/jeong-yun-lim.xcuserdatad/UserInterfaceState.xcuserstate
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcuserdata/jeong-yun-lim.xcuserdatad/xcschemes/xcschememanagement.plist
  HalfFifty_FE/HalfFifty_Watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  HalfFifty_FE/HalfFifty_Watch Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  HalfFifty_FE/HalfFifty_Watch Watch App/Assets.xcassets/Contents.json
  HalfFifty_FE/HalfFifty_Watch Watch App/ContentView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/HalfFifty_WatchApp.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/Preview Content/Preview Assets.xcassets/Contents.json
Labels: 🥰 FrontEnd, 🎨 Html&css

#107 Chore: Mediapipe 연동을 위한 세팅
  .gitignore
  HalfFifty_FE/.ruby-version
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcuserdata/minmin.xcuserdatad/xcschemes/xcschememanagement.plist
  HalfFifty_FE/Podfile
  HalfFifty_FE/Podfile.lock
Labels: 🥰 FrontEnd, ⚙️ Setting

#108 Test : CI/CD
  .github/workflows/backend-ci-cd.yml
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#109 Fix : CI/CD Test를 위한 코드 수정
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#110 Fix : Build시 JAR파일 존재하는지 확인하는 로직 추가
  .github/workflows/backend-ci-cd.yml
Labels: 🐞 BugFix

#111 Test : CI/CD Deploy 테스트
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#112 Fix : Deploy jobs 단계 시 경로 수정
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#114 Test : CD Test를 위한 코드 수정
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#115 Fix : .pem 파일 권한 설정
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#116 Design: 스마트워치 음성변환 화면 퍼블리싱
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.xcworkspace/xcuserdata/jeong-yun-lim.xcuserdatad/UserInterfaceState.xcuserstate
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcuserdata/jeong-yun-lim.xcuserdatad/xcschemes/xcschememanagement.plist
  HalfFifty_FE/HalfFifty_Watch Watch App/ContentView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/VoiceTransformView.swift
  HalfFifty_FE/Podfile
  HalfFifty_FE/Podfile.lock
Labels: 🥰 FrontEnd, 🎨 Html&css

#118 Fix : 버전 수정
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#119 Test : SSH 접속 테스트 로직 추가
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#120 Feat : 호스트 키 등록 로직 추가
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#121 Fix : pem키 파일 경로 변경
  .github/workflows/backend-ci-cd.yml
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/HealthCheck.java
Labels: 🐞 BugFix, ✅ Test, 🐈‍⬛ BackEnd

#123 Design: 키워드 관리 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_Watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  HalfFifty_FE/HalfFifty_Watch Watch App/KeywordView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/VoiceTransformView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#125 Design: 키워드 관리 페이지 퍼블리싱 메인에 Merge
  HalfFifty_FE/HalfFifty_Watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  HalfFifty_FE/HalfFifty_Watch Watch App/KeywordView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/VoiceTransformView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#134 Fix 메뉴 바 오류 수정 및 Header 그림자 제거
  HalfFifty_FE/HalfFifty_FE/ContentView.swift
  HalfFifty_FE/HalfFifty_FE/MainView.swift
Labels: 🐞 BugFix, 🥰 FrontEnd, 🎨 Html&css, 🔨 Refactor

#138 Feat : 유저 회원가입 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/bean/SaveUserBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/bean/small/CreateUserDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/bean/small/SaveUserDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/controller/UserController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/domain/DTO/RequestUserSaveDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/domain/UserDAO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/repository/UserRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/service/UserService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#136 Feat: 음성 녹음 텍스트화 기능 추가
  HalfFifty_FE/HalfFifty_Watch Watch App/ContentView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/KeywordView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/VoiceTransformView.swift
Labels: ✨ Feature, 🥰 FrontEnd

#139 Feat : 키워드 등록 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/SaveKeywordBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/small/CreateKeywordDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/small/SaveKeywordDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/controller/KeywordController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/domain/DTO/RequestKeywordSaveDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/domain/KeywordDAO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/repository/KeywordRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/service/KeywordService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#140 Feat : 키워드 수정 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/UpdateKeywordBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/small/GetKeywordDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/controller/KeywordController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/domain/DTO/RequestKeyWordUpdateDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/repository/KeywordRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/service/KeywordService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#144 키워드 삭제 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/DeleteKeywordBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/small/DeleteKeywordDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/controller/KeywordController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/domain/DTO/RequestKeywordDeleteDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/service/KeywordService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#145 Feat : 키워드 조회 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/GetKeywordsBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/small/CreateKeywordsDTOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/small/GetKeywordsDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/controller/KeywordController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/domain/DTO/ResponseKeywordGetDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/repository/KeywordRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/service/KeywordService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#147 Fix : Keyword
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/bean/DeleteKeywordBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/controller/KeywordController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/keyword/service/KeywordService.java
Labels: 🐞 BugFix, 📬 API, 🐈‍⬛ BackEnd
