Repository 2025TUKCOMCD/HalfFifty, pull requests merged in 2025-02, with the labels that each got.

#148 Feat: mediapipe를 통한 손가락 랜드마크 및 마디 연결선 출력
  .gitignore
  HalfFifty_FE/HalfFifty_FE.xcodeproj/project.pbxproj
  HalfFifty_FE/HalfFifty_FE/CameraView.swift
  HalfFifty_FE/HalfFifty_FE/MainView.swift
  HalfFifty_FE/HalfFifty_FE/ViewController/CameraViewController.swift
Labels: ✨ Feature, 🥰 FrontEnd

#151 Feat : 유저 프로필 조회 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/bean/GetUserBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/bean/small/CreateUserDTOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/bean/small/GetUserDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/controller/UserController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/domain/DTO/ResponseUserGetDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/service/UserService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#152 Feat : 유저 닉네임 수정 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/bean/UpdateUserBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/controller/UserController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/domain/DTO/RequestUserUpdateDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/user/service/UserService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#153 Design: 사용자 정보 페이지 및 닉네임 변경 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE/MenuView.swift
  HalfFifty_FE/HalfFifty_FE/View/CameraView.swift
  HalfFifty_FE/HalfFifty_FE/View/ContentView.swift
  HalfFifty_FE/HalfFifty_FE/View/MainView.swift
  HalfFifty_FE/HalfFifty_FE/View/MenuView.swift
  HalfFifty_FE/HalfFifty_FE/View/NicknameEditView.swift
  HalfFifty_FE/HalfFifty_FE/View/SplashView.swift
  HalfFifty_FE/HalfFifty_FE/View/UserView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#156 Feat: 사용자 정보 조회 API 연동 및 닉네임 수정 기능 구현
  HalfFifty_FE/HalfFifty-FE-Info.plist
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcshareddata/xcschemes/HalfFifty_FE.xcscheme
  HalfFifty_FE/HalfFifty_FE.xcodeproj/xcshareddata/xcschemes/HalfFifty_Watch Watch App.xcscheme
  HalfFifty_FE/HalfFifty_FE/Model/UserModel.swift
  HalfFifty_FE/HalfFifty_FE/View/ContentView.swift
  HalfFifty_FE/HalfFifty_FE/View/MenuView.swift
  HalfFifty_FE/HalfFifty_FE/View/NicknameEditView.swift
  HalfFifty_FE/HalfFifty_FE/View/Setting/SettingView.swift
  HalfFifty_FE/HalfFifty_FE/View/User/NicknameEditView.swift
  HalfFifty_FE/HalfFifty_FE/View/User/UserView.swift
  HalfFifty_FE/HalfFifty_FE/ViewModel/UserViewModel.swift
Labels: ✨ Feature, 🥰 FrontEnd

#157 Design: 설정 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE/View/MenuView.swift
  HalfFifty_FE/HalfFifty_FE/View/Setting/SettingView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#158 Design: 글자 크기 설정 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE/HalfFifty_FEApp.swift
  HalfFifty_FE/HalfFifty_FE/View/Setting/FontSizeSettingView.swift
  HalfFifty_FE/HalfFifty_FE/View/Setting/SettingView.swift
  HalfFifty_FE/HalfFifty_FE/ViewModel/FontSizeManager.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#159 Design: FAQ 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE/View/Setting/FAQView.swift
  HalfFifty_FE/HalfFifty_FE/View/Setting/SettingView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#160 Design: 질문하기 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE/View/Setting/InquiryView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#161 Desgin: 고객센터 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE/View/Setting/CustomerCenterView.swift
  HalfFifty_FE/HalfFifty_FE/View/Setting/SettingView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#149 Feat: 키워드 인식 기능 개발
  HalfFifty_FE/HalfFifty-Watch-Watch-App-Info.plist
  HalfFifty_FE/HalfFifty_FE/STTManager.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/AudioRecorderManager.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/ContentView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/KeywordView.swift
  HalfFifty_FE/HalfFifty_Watch Watch App/WatchNotificationManager.swift
Labels: ✨ Feature, 🥰 FrontEnd

#162 Design: 키워드 세팅 페이지 퍼블리싱
  HalfFifty_FE/HalfFifty_FE/View/Keyword/KeywordAddView.swift
  HalfFifty_FE/HalfFifty_FE/View/Keyword/KeywordSettingView.swift
  HalfFifty_FE/HalfFifty_FE/View/MenuView.swift
Labels: 🥰 FrontEnd, 🎨 Html&css

#163 Feat: 모바일 키워드 설정 페이지 기능 추가
  HalfFifty_FE/HalfFifty_FE/View/Keyword/KeywordAddView.swift
  HalfFifty_FE/HalfFifty_FE/View/Keyword/KeywordSettingView.swift
Labels: ✨ Feature, 🥰 FrontEnd

#165 FAQ 전체조회 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/FaqSaveBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/GetFaqsBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/CreateFaqsDTOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/GetFaqsDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/controller/FaqController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/domain/DTO/ResponseFaqGetDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/domain/FaqDAO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/service/FaqService.java
Labels: 📬 API, 🐈‍⬛ BackEnd

#166 Feat : AQ 유저 등록 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/AqUserSaveBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/CreateAqUserDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/SaveAqUserDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/controller/AqController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/domain/AqDAO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/domain/DTO/RequestAqUserSaveDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/repository/AqRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/service/AqService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#167 AQ Admin 답장 API(관리자용)
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/AqUserSaveBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/UpdateAqAdminBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/GetAqDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/SaveAqDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/controller/AqController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/domain/DTO/RequestAqAdminUpdateDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/service/AqService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#168 Feat : AQ 전체조회 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/GetAqsBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/CreateAqsDTOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/GetAqsDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/controller/AqController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/domain/DTO/ResponseAqGetDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/repository/AqRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/service/AqService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#169 Feat : AQ 삭제 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/DeleteAqBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/DeleteAqDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/bean/small/GetAqDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/controller/AqController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/domain/DTO/RequestAqDeleteDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/repository/AqRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/FAQ/service/AqService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#171 Feat: 튜토리얼 페이지 추가
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-1.imageset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-1.imageset/tutorial-1.png
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-2.imageset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-2.imageset/tutorial-2.png
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-3.imageset/Contents.json
  HalfFifty_FE/HalfFifty_FE/Assets.xcassets/tutorial-3.imageset/tutorial-3.png
  HalfFifty_FE/HalfFifty_FE/View/ContentView.swift
  HalfFifty_FE/HalfFifty_FE/View/MenuView.swift
  HalfFifty_FE/HalfFifty_FE/View/TutorialView.swift
Labels: ✨ Feature, 🥰 FrontEnd, 🎨 Html&css

#150 Feat : 수화인식 API
  HalfFifty_BE/build.gradle
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/FlaskSignLanguageBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/SaveTranslationBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/small/CreateTranslationDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/small/CreateTranslationDTOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/small/SaveTranslationDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/controller/TranslationController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/domain/DTO/RequestSignLanguageDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/domain/DTO/ResponseTranslationGetDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/domain/TranslationDAO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/repository/TranslationRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/service/TranslationService.java
  HalfFifty_BE/src/main/resources/application.properties
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd

#177 Fix : 수화 관련 로직 수정
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/FlaskSignLanguageBean.java
  HalfFifty_BE/src/main/resources/application.properties
Labels: 📬 API

#178 Feat: FAQ 페이지 API 연동
  HalfFifty_FE/HalfFifty_FE/View/Setting/FAQView.swift
Labels: ✨ Feature, 🥰 FrontEnd

#179 Feat : 번역 기록 삭제 API
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/DeleteTranslationBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/small/DeleteTranslationDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/bean/small/GetTranslationDAOBean.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/controller/TranslationController.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/domain/DTO/RequestTranslationDeleteDTO.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/repository/TranslationRepositoryJPA.java
  HalfFifty_BE/src/main/java/HalfFifty/HalfFifty_BE/translation/service/TranslationService.java
Labels: ✨ Feature, 📬 API, 🐈‍⬛ BackEnd
